# Generated by Django 2.2.4 on 2019-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('citizenship_id', models.AutoField(primary_key=True, serialize=False)),
                ('citizenship_name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Citizenship',
                'verbose_name_plural': 'Citizenships',
                'ordering': ['citizenship_name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=70, verbose_name='Name')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=70, verbose_name='Name')),
                ('currency_symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['currency_name'],
            },
        ),
    ]
