# Generated by Django 2.2.4 on 2019-08-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality_name', models.CharField(max_length=200, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
    ]
